### PR TITLE
A relaxed origin validator

### PR DESCRIPTION
**Pull request by onne**
The spec mandates a relaxed same origin restriction, as opposed to an equality test - see https://www.w3.org/TR/webauthn/#determines-the-set-of-origins-on-which-the-public-key-credential-may-be-exercised.

This change includes:
- A `RelaxedOriginValidator`.
- A respective relaxed matcher method in the `Origin` class.
- Allows to set an origin validator on `Manager` and `DataValidator` classes. Default is still the usual `OriginValidator`.

The default `OriginValidator` is unchanged, except for being exposed to referring classes.

### CODE REVIEW

**Comment by ynojima** [comment]
Hi, Thank you for the pull-request!
The section you cited is about "RP ID" not "Origin".
The rule for "RP ID" is relaxed for sharing a credential between origin's effective domain, and its registrable sub-domain (ex. example.com and sub.example.com), 
but the regulation for "Origin" is not relaxed. The objective of matching "Origin" is to make sure the "Origin" the user agent (browser) knows is same as what the server expected to protect users from the MITM attack.
I think there is no need to relax the regulation for "Origin". Please correct me if my understanding is wrong.
If you really need to make domain and its sub-domain valid at the same time, you may set specify them in `ServerProperty`'s constructor.

**Comment by onne** [comment]
Hi Yoshikazu,
Sorry  for the late response. I understand your objection to relaxing the regulation for "Origin".
Will you be open to consider accepting a change that will allow to override the default `OriginValidator` on `*Manager` and `*DataValidator` classes? The change request will not introduce any change to existing constructors but rather an additional constructor with additional `originValidator` parameter will be introduced.
Thanks

**Comment by ynojima** [comment]
Now I understand the needs for relaxing Origin validation. I'll explore how to implement it.

**Comment by onne** [comment]
Following up on this. Is there anything I can do to help with this?

**Comment by ynojima** [comment]
Sorry for taking time. I'll take time next week.

**Comment by ynojima** [comment]
I made a pull-request #459 to resolve this issue. Could you check that meet your requirements?

**Comment by ynojima** [comment]
@onne Could you check #459 whether it meets your requirements?

**Comment by onne** [comment]
Close due to https://github.com/webauthn4j/webauthn4j/pull/459

**Pull request closed without merging**
