### PR TITLE
Make AlternativeDescriptions.java immutable

### PR DESCRIPTION
**Pull request by DavidAdamczyk**

### CODE REVIEW

**Comment by ynojima** [comment]
Thank you for your pull-request!

Immutable map should pass following test case, but your `AlternativeDescriptions` seems not.
```
    @Test
    void entrySet_remove_test(){
        Map<String, String> source = new HashMap<>();
        source.put("key", "value");
        AlternativeDescriptions target = new AlternativeDescriptions(source);
        assertThrows(UnsupportedOperationException.class,
                () -> target.entrySet().remove(target.entrySet().iterator().next())
        );
    }
```

WebAuthn4J has `AbstractImmutableMap`, which can be used as super class for immutable map.
AlternativeDescriptions should inherit `AbstractImmutableMap` as AuthenticationExtensionsAuthenticatorInputs does.

**Comment by ynojima** [comment]
BTW, it seems the email address you are using for signing commit is different from the one registered for your GitHub account.
I supporse it is better to register your email address to your GitHub account for expressing your contribution.

**Comment by DavidAdamczyk** [comment]
Thank you very much for info about AbstractImmutableMap. The fix has been committed. 

And email address has been changed to Github account address.

**Comment by ynojima** [comment]
Thank you for update. Now your code itself is ready to be merged.

It seems your last commit still be bound to `david.adamczyk@ness.com` [1], but you use `davidadamczyk@icloud.com` on GitHub. 
Please amend your commit [2] or change your e-mail address on GitHub if you want. 

[1]
```
commit 22ba3ac8ea4aa5ad23f7264d8be33abc06b73ae3
Author:     David Adamczyk <david.adamczyk@ness.com>
AuthorDate: Sun Mar 3 09:46:54 2019 +0100
Commit:     David Adamczyk <david.adamczyk@ness.com>
CommitDate: Sun Mar 3 09:46:54 2019 +0100

    Changed immutableAlternativeDescriptions to AbstractImmutableMap
```

[2]
```
git config --global user.email davidadamczyk@icloud.com
git commit --amend --author="David Adamczyk <davidadamczyk@icloud.com>"
```

**Comment by DavidAdamczyk** [comment]
The email address has been changed to davidadamczyk@icloud.com

**Pull request merged**
