### PR TITLE
Static secure random

### PR DESCRIPTION
**Pull request by kvandermast**
We've run into a problem that the seeding on creating new SecureRandoms takes too much time (taking up more than 20 - 25s/req). We foresee a large load, so my suggestion would be to make this static/factory based. What do you think?

### CODE REVIEW

**Comment by ynojima** [comment]
Thank you for pointing out. That need to be improved. will look into your pull-request.

**Comment by ynojima** [comment]
`SecureRandomFactory` sounds like factory class for `SecureRandom`, but it isn't. It's confusing.

BTW, since SecureRandom is only used in test code or test utilities, it won't be overhead for request processing.

**Comment by ynojima** [comment]
As I suppose having `SecureRandom` per classes won't make large overhead, I made PR without factory.
https://github.com/webauthn4j/webauthn4j/pull/85

**Comment by kvandermast** [comment]
As long as it is only created once, it will not be a large overhead. 

I first called the `SecureRandomFactory` a `SecureRandomHelper`, then a `SecureRandomUtil`... I wasn't convinced by the naming either. Have a SecureRandomUtil/-Helper class which is publicly available would be a plus too, as you can suggest users, for generating a challenge for the options, to use that class. Avoiding overhead on that side again.

It's not the first time that I notice that I change code that is solely used for test purposes (e.g. being in the util module). Isn't there a way to regroup the classes so that, if they are only used for unit testing, are moved to the `test` module?

**Comment by ynojima** [comment]
> Have a SecureRandomUtil/-Helper class which is publicly available would be a plus too, as you can suggest users, for generating a challenge for the options, to use that class. Avoiding overhead on that side again.

Hmm, good point. I recalled that `SecureRandom` is used inside `DefaultChallenge`. `DefaultChallenge` uses `UUID` to generate a random byte array, and `UUID` uses `SecureRandom` and cache it in the static field.

> It's not the first time that I notice that I change code that is solely used for test purposes (e.g. being in the util module). Isn't there a way to regroup the classes so that, if they are only used for unit testing, are moved to the test module?

Sorry for confusion. `KeyUtil` class is better to be moved to `test` module. will do.

**Pull request closed without merging**
