### PR TITLE
Adding nullable to Options inside AuthenticatorGetInfo

### PR DESCRIPTION
**Pull request by billlyd123**
This will resolve an issue with Serialization/ Deserialization when only some of the options are present. Discussion post here: https://github.com/webauthn4j/webauthn4j/discussions/797

### CODE REVIEW

**Comment by ynojima** [comment]
Sorry for overlooking the topic in the Discussions.  I'm on vacation and will check no later than the 18th.

**Comment by ynojima** [comment]
Thank you for your fix. Now it is merged into master.

**Comment by billlyd123** [comment]
Do you know when the next release will be?

**Comment by ynojima** [comment]
WebAuthn4J is released on the 1st of every month. So, next release will be  Aug. 1st.

**Pull request merged**
